# Generated by Django 4.0.6 on 2022-08-01 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('desc', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ficha_tecnica', models.TextField()),
                ('costo', models.IntegerField()),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planta.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planta.producto')),
                ('Trabajador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planta.trabajador')),
            ],
        ),
    ]
