# Generated by Django 4.0.6 on 2022-08-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0003_produccion_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='color',
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
